### ISSUE TITLE
problem with iexpoler quirk mode

### ISSUE THREAD

**Issue by nexus061** [nerdErg/AjaxAnywhere#32]
in javascript function AjaxAnywhere.retrieveTags

 tagsArray.push($('#' + value.trim()).prop('tagName').toLowerCase());

not work in iexplorer in compatibility mode and quirk mode.

I have changed with

 tagsArray.push($('#' + $.trim(value)).prop('tagName').toLowerCase());

and it work

best regards

**Comment by aruizca** [comment]
Thanks @nexus061!!

I will add the change in the upcoming version 2,1

Cheers,
